### ISSUE TITLE
Etherpad

### ISSUE THREAD

**Issue by widdowquinn** [olexandr-konovalov/2017-05-18-standrews#10]
There's currently no link to the course Etherpad on the webpage.

Is there one created but not linked? If not, I'll create one at [http://pad.software-carpentry.org/2017-05-18-standrews](http://pad.software-carpentry.org/2017-05-18-standrews), populate with links/download files etc. to match the last course, and add to the webpage.

**Comment by olexandr-konovalov** [comment]
Thanks - please do!

**Comment by olexandr-konovalov** [comment]
http://pad.software-carpentry.org/2017-05-18-standrews works now, and the link is already on the page.
