### ISSUE TITLE
Default branch for GitHub

### ISSUE THREAD

**Issue by widdowquinn** [olexandr-konovalov/2017-05-18-standrews#4]
Should we make the default branch for the repo be `gh-pages`? That is the branch that feeds the website, and that learners see when they first come to the repo. At the moment the default is `2017.02`, to which we're not pushing new material. This has caught me out a couple of times, also.

**Comment by olexandr-konovalov** [comment]
Good idea - done. Leftover from importing the workshop page template from SWC.
